spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  server:
    error:
      include-message: always
  logging:
    level:
      io.r2dbc.postgresql.QUERY: DEBUG
      io.r2dbc.postgresql.PARAM: DEBUG
